config/routes.rb
EcaTracker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars

  namespace 'api' do
    namespace 'v1' do
      resources :stages, :defaults => { :format => 'json' }
      resources :cars, :defaults => { :format => 'json' } do 
        resources :stage_assignments, :defaults => { :format => 'json' }
      end
    end
  end

	match 'stats' => 'stats#index'


  root to: 'cars#index'

end

app/views/admin/dashboard/_active_cars.html.erb
<table class="active_vehicles">
  <thead>
    <th>Code</th>
    <th>Make</th>
    <th>Model</th>
    <th>Stage</th>
    <th>Actions</th>
  </thead>
  <tbody>
  </tbody>
</table>
<script type="text/javascript">
  var activeAssignments = new EcaTrackerApp.StageAssignmentCollection();

  activeAssignments.reset(<%= active_assignments.to_json(include: [:car, :stage]).html_safe %>);

  var activeAssignmentsCollectionView = new EcaTrackerApp.AssignmentsCollectionView({
        collection: activeAssignments,
        el: $('table.active_vehicles')
      }).render();
</script>

app/views/admin/dashboard/_inactive_cars.html.erb
<table class="inactive_vehicles">
  <thead>
    <th>Code</th>
    <th>Make</th>
    <th>Model</th>
    <th>Stage</th>
    <th></th>
  </thead>
  <tbody>
  </tbody>
</table>
<script type="text/javascript">
  var inactiveAssignments = new EcaTrackerApp.StageAssignmentCollection();

  inactiveAssignments.reset(<%= inactive_assignments.to_json(include: [:car, :stage]).html_safe %>);

  var inactiveAssignmentsCollectionView = new EcaTrackerApp.AssignmentsCollectionView({
        collection: inactiveAssignments
      }).render();
</script>

app/views/admin/dashboard/_incomplete_cars.html.erb
<script src="/assets/application.js" type="text/javascript" ></script>
<script type="text/javascript">
  var stages = new EcaTrackerApp.StageCollection();
  stages.reset(<%= stages.html_safe %>);
  var router = new EcaTrackerApp.Router({stages: stages, uid: <%= current_admin_user.id %>, car_collection: <%= Rabl::Renderer.json(cars, 'api/v1/cars/index', :view_path => 'app/views').html_safe %> });
  Backbone.history.start();
</script>
<link href="/assets/bootstrap_and_overrides.css?body=1" media="all" rel="stylesheet" type="text/css" />
<div>
	<%= paginate cars %>
</div>

app/views/admin/dashboard/_style_include.html.erb
<link href="/assets/bootstrap_and_overrides.css?body=1" media="all" rel="stylesheet" type="text/css" />