config/routes.rb
EcaTracker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars

  namespace 'api' do
    namespace 'v1' do
      resources :stages, :defaults => { :format => 'json' }
      resources :cars, :defaults => { :format => 'json' } do 
        resources :stage_assignments, :defaults => { :format => 'json' }
      end
    end
  end

	match 'stats' => 'stats#index'


  root to: 'cars#index'

end

app/models/stage.rb
class Stage < ActiveRecord::Base
  attr_accessible :title, :deleted

  has_many :stage_assignments
  has_many :cars, through: :stage_assignments

  validates_presence_of :title
	
	#default_scope where(:deleted => false);

	def destroy
		self.deleted = true;
		self.save
	end

	def delete
		self.destroy
	end

end

app/controllers/api/v1/stages_controller.rb
module Api
  module V1
    class StagesController < ApplicationController
      ##
      # Takes 'title' as parameter in url
      #
      def index
        if(params[:title])
          #@stages = Stage.find_all_by_title(params[:title])
          @stages = Stage.find(:first, :conditions => ['lower(title) = ?', params[:title].downcase])
        else
          @stages = Stage.where(:deleted => false)
        end
        respond_to do |format|
          format.json { render json: @stages }
        end
      end

      def show
        @stage = Stage.find(params[:id])

        respond_to do | format |
          format.json { render json: @stage }
        end
      end

    end
  end
end

app/controllers/stages_controller.rb
class StagesController < InheritedResources::Base
end

app/helpers/stages_helper.rb
module StagesHelper
end

app/views/stages/_form.html.erb
<%= form_for(@stage) do |f| %>
  <% if @stage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage.errors.count, "error") %> prohibited this stage from being saved:</h2>

      <ul>
      <% @stage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stages/edit.html.erb
<h1>Editing stage</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage %> |
<%= link_to 'Back', stages_path %>

app/views/stages/index.html.erb
<h1>Listing stages</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stages.each do |stage| %>
  <tr>
    <td><%= stage.title %></td>
    <td><%= link_to 'Show', stage %></td>
    <td><%= link_to 'Edit', edit_stage_path(stage) %></td>
    <td><%= link_to 'Destroy', stage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stage', new_stage_path %>

app/views/stages/new.html.erb
<h1>New stage</h1>

<%= render 'form' %>

<%= link_to 'Back', stages_path %>

app/views/stages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @stage.title %>
</p>


<%= link_to 'Edit', edit_stage_path(@stage) %> |
<%= link_to 'Back', stages_path %>