config/routes.rb
EcaTracker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars

  namespace 'api' do
    namespace 'v1' do
      resources :stages, :defaults => { :format => 'json' }
      resources :cars, :defaults => { :format => 'json' } do 
        resources :stage_assignments, :defaults => { :format => 'json' }
      end
    end
  end

	match 'stats' => 'stats#index'


  root to: 'cars#index'

end

app/models/stage_assignment.rb
class StageAssignment < ActiveRecord::Base
  attr_accessible :car_id, :stage_id, :time_in, :time_out, :admin_user_id
  # Add validation to prevent multiple stage assignments from being open
  # this particular validation prevents a stage assignment from being updated.
  #validate :has_no_active_stage_assignments_for_car
  belongs_to :car
  belongs_to :stage
  belongs_to :admin_user

  validates_presence_of :stage_id, :car_id

  def is_open?
    self.time_in and !self.time_out
  end

  def has_no_active_stage_assignments_for_car
    if self.time_out == nil && self.car.has_open_stage_assignments?
      self.errors.add(:car, "car already has open stage assignments") 
    end
  end

  def last_modified_by
    self.admin_user.email
  end

end

app/controllers/api/v1/stage_assignments_controller.rb
module Api
  module V1
    class StageAssignmentsController < ApplicationController
      def index
        @stage_assignments = StageAssignment.find_all_by_car_id(params[:car_id])
      end

      def show
        @stage_assignment = StageAssignment.find_by_id(params[:id])
      end

      def edit
        @stage_assignment = StageAssignment.find_by_id(params[:id])

        respond_to do | format |
          if @stage_assignment.update_attributes(params[:stage_assignment])
            format.json { head :no_content }
          else
            format.json { render json: @stage_assignment.errors, status: :unprocessable_entity }
          end
        end
      end

      def update
        @stage_assignment = StageAssignment.find(params[:id])
        respond_to do | format |
          if @stage_assignment.update_attributes(params[:stage_assignment])
            format.json { render json: @stage_assignment }
          else
            format.json { render json: @stage_assignment.errors, status: :unprocessable_entity }
          end
        end
      end

      def create
        @stage_assignment = StageAssignment.new(params[:stage_assignment])
        respond_to do | format |
          if(@stage_assignment.save)
            format.json { render json: @stage_assignment }
          else
            format.json { render json: @stage_assignment.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end
end

app/controllers/stage_assignments_controller.rb
class StageAssignmentsController < InheritedResources::Base
end

app/helpers/stage_assignments_helper.rb
module StageAssignmentsHelper
end

app/views/stage_assignments/_form.html.erb
<%= form_for(@stage_assignment) do |f| %>
  <% if @stage_assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stage_assignment.errors.count, "error") %> prohibited this stage_assignment from being saved:</h2>

      <ul>
      <% @stage_assignment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stage_id %><br />
    <%= f.number_field :stage_id %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br />
    <%= f.number_field :car_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stage_assignments/edit.html.erb
<h1>Editing stage_assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @stage_assignment %> |
<%= link_to 'Back', stage_assignments_path %>

app/views/stage_assignments/index.html.erb
<h1>Listing stage_assignments</h1>

<table>
  <tr>
    <th>Stage</th>
    <th>Car</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stage_assignments.each do |stage_assignment| %>
  <tr>
    <td><%= stage_assignment.stage_id %></td>
    <td><%= stage_assignment.car_id %></td>
    <td><%= link_to 'Show', stage_assignment %></td>
    <td><%= link_to 'Edit', edit_stage_assignment_path(stage_assignment) %></td>
    <td><%= link_to 'Destroy', stage_assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stage assignment', new_stage_assignment_path %>

app/views/stage_assignments/new.html.erb
<h1>New stage_assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', stage_assignments_path %>

app/views/stage_assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stage:</b>
  <%= @stage_assignment.stage_id %>
</p>

<p>
  <b>Car:</b>
  <%= @stage_assignment.car_id %>
</p>


<%= link_to 'Edit', edit_stage_assignment_path(@stage_assignment) %> |
<%= link_to 'Back', stage_assignments_path %>