config/routes.rb
EcaTracker::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars

  namespace 'api' do
    namespace 'v1' do
      resources :stages, :defaults => { :format => 'json' }
      resources :cars, :defaults => { :format => 'json' } do 
        resources :stage_assignments, :defaults => { :format => 'json' }
      end
    end
  end

	match 'stats' => 'stats#index'


  root to: 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible :code, :make, :model, :deleted

  has_many :stage_assignments, :dependent => :destroy
  has_many :stages, :through => :stage_assignments, :dependent => :destroy

	# Active admin needs this commented out
	#default_scope where(:deleted => false);

  validates_presence_of :code, :make, :model

	validates_uniqueness_of :code

  def title
    self.code + ' - ' + self.make + ' ' + self.model
  end

  def has_open_stage_assignments?
    self.stage_assignments.map { | sa |
      sa.is_open?
    }.include?(true)
  end

  def active_stages
    self.stage_assignments.select { | sa |
      sa.stage if sa.is_open?
    }.map { | sa |
      sa.stage
    }
  end

  def active_stage
    self.active_stages.first
  end

	def active_stage_title
		stage = self.active_stage
		if stage then
			return stage.title
		end
		''
	end

	def active_assignment
		self.stage_assignments.select { |sa|
			sa if sa.is_open?
		}.last
	end

	def active_assignments
		self.stage_assignments.select { |sa|
			sa if sa.is_open?
		}
	end

	def destroy
		self.deleted = true;
		self.save
	end

	def delete
		self.destroy
	end

	def days_in_stage
		sa = self.stage_assignments.last
		return 0 unless sa != nil

		return (Date.today - Date.parse(sa.time_in.to_s)).to_i unless sa.time_out != nil
		return (Date.parse(sa.time_out.to_s) - DateTime.parse(sa.time_in.to_s)).to_i
	end
end

app/controllers/api/v1/cars_controller.rb
module Api
  module V1
    class CarsController < ApplicationController
      def index
        if(params[:code])
          @cars = Car.find_all_by_code(params[:code])
        else
          @cars = Car.where(:deleted => false);
        end
      end

      def show
        @car = Car.find_by_id(params[:id])
      end

      def update
        @car = Car.find(params[:id])
        respond_to do | format |
          if @car.update_attributes(params[:car])
            format.json { render json: @car }
          else
            format.json { render json: @car.errors, status: :unprocessable_entity }
          end
        end
      end

      def create
        @car = Car.new(params[:car])
        respond_to do | format |
          if(@car.save)
            format.json { render json: @car}
          else
            format.json { render json: @car.errors, status: :unprocessable_entity }
          end
        end
      end
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < InheritedResources::Base
  respond_to :html, :json

  def index
    if params[:search] then
      @cars = Car.where("code LIKE ? and deleted = ?", "%#{params[:search]}%", false).page params[:page]
    else
      @cars = Car.page params[:page]
    end
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<div style="padding-top: 50px" class="row">
  <h2 class="span6">Cars In Inventory</h2>
  <form src="<%= url_for :cars %>" method="GET" class="span6">
    <input id="search" name="search" type="text" placeholder="Type code here"/>
    <button type="submit" class="btn">Search</button>
  </form>
</div>
<div class="row">
<% if @cars != nil then %>
<table class="table-striped span12">
  <thead>
    <th>Code</th>
    <th>Make</th>
    <th>Model</th>
    <th>Current Stage</th>
    <th>Previous Stage</th>
  </thead>
  <tbody>
<% @cars.each do |car| %>
  <tr>
    <td><%= car.code %></td>
    <td><%= car.make %></td>
    <td><%= car.model %></td>
    <td><%= begin car.active_stages.first.title rescue '' end %></td>
    <td><%= begin car.stage_assignments.select{|x| x.time_out != nil }.first.stage.title rescue '' end%></td>
  </tr>
<% end %>
</tbody>
</table>
</div>
<% end %>
<%= paginate @cars %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @car.make %>
</p>

<p>
  <b>Model:</b>
  <%= @car.model %>
</p>

<p>
  <b>Code:</b>
  <%= @car.code %>
</p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>